### ISSUE TITLE
problem in execution?

### ISSUE THREAD

**Issue by massimiliano-dalcero** [BlackHat-Ashura/Reflective_PE_Loader#1]
Hello :)
Congratulations, for your very interesting project :)
I'm trying it for study purposes, and in my lab testing, I'm attempting to execute:

`Reflective_PE_Loader.exe EXE C:\Windows\System32\calc.exe`

Analyzing the execution, I noticed that it reaches up to
`exe_entry_addr()`

Is there something I'm not understanding? (very likely) :)

**Comment by BlackHat-Ashura** [comment]
Hey @massimiliano-dalcero 

I already came across the same issue. I wasn't sure why, seems the issue is that `calc.exe` is a **GUI program** so it'll have a different entry point signature.
I'm yet to check this fix.

Check with any **console program** with the main function signature as `BOOL(WINAPI* main)();`

**Comment by massimiliano-dalcero** [comment]
I managed to run other .exe but I didn't understand why it didn't run anything else.  Thanks for your feedback  😊
Thanks for your feedback 😊

could it be that the Windows GUI application main is named WinMain?

**Comment by BlackHat-Ashura** [comment]
Yes for GUI applications the function signature is as that of `WinMain` or `wWinMain`

A friend of mine helped me fix this issue. [@dosxuz](https://github.com/dosxuz)
The below change is able to execute `calc.exe`

```
#include <Windows.h>
#include <iostream>
#include <stdio.h>


struct PE {
	DWORD64 base;
	DWORD64 entry = NULL;
};

typedef int(WINAPI* pEXEEntry)(HINSTANCE, HINSTANCE, LPSTR, int);

#include "PE Mapper.hpp"

int WinMain(HINSTANCE hInst, HINSTANCE hInstPrev, PSTR cmdline, int cmdshow) {
	HANDLE hPE = ::CreateFileA("C:\\Windows\\System32\\calc.exe", GENERIC_READ, NULL, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
	DWORD pe_size = ::GetFileSize(hPE, NULL);
	void* pe_content = ::HeapAlloc(::GetProcessHeap(), HEAP_ZERO_MEMORY, pe_size);
	::ReadFile(hPE, pe_content, pe_size, NULL, NULL);
	::CloseHandle(hPE);

	PE pe = MapPE((BYTE*)pe_content);
	::HeapFree(::GetProcessHeap(), NULL, pe_content);

	pEXEEntry exe_entry_addr = (pEXEEntry)pe.entry;
	// printf("exe_entry_addr : %p", exe_entry_addr);
	exe_entry_addr(hInst, hInstPrev, cmdline, cmdshow);

	::Sleep(INFINITE);
	::VirtualFree((LPVOID)pe.base, NULL, MEM_RELEASE);
}
```
